export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREMENT_ITEM_QUANTITY = 'INCREMENT_ITEM_QUANTITY';
export const DECREMENT_ITEM_QUANTITY = 'DECREMENT_ITEM_QUANTITY';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT'


export const REQUEST_ACTION = 'REQUEST_ACTION'
export const REQUEST_FAIL = 'REQUEST_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'